openapi: 3.0.0
info:
  title: Character Generator
  description: 'An API to generate and interact with any character you can imagine!'
  version: 0.0.1
servers:
  - url: https://f3e5uzg5tb.execute-api.eu-central-1.amazonaws.com
    description: Main (production) URL
  - url: https://f3e5uzg5tb.execute-api.eu-central-1.amazonaws.com/dev
    description: Dev deployment URL
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Message:
      type: object
      properties:
        name:
          type: string
          description: Name of the sender
        timestamp:
          type: number
          format: timestamptz
          description: Timestamp of the message
        text:
          type: string
          description: Message text
    Chat:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Chat ID
        created_at:
          type: number
          format: timestamptz
          description: Creation timestamp of the chat
          default: now
        initial_prompt:
          type: string
          description: Initial prompt sent to ChatGPT for the conversation
        character_id:
          type: integer
          format: int64
          description: ID of the character associated with the chat
        user_id:
          type: integer
          format: int64
          description: ID of the user associated with the chat
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
    Character:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Character ID
        created_at:
          type: string
          format: date-time
          description: Creation timestamp of the character
          default: now
        name:
          type: string
          description: Character name
        description:
          type: string
          description: Character bio
        properties:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: "The name of the property"
              value:
                type: string
                description: "The value of the property"
        user_id:
          type: integer
          format: int64
          description: ID of the user who created the character
    Unauthorized:
      type: object
      properties:
        message:
          type: string
          description: Error message
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error code
        error_description:
          type: string
          description: Error description
paths:
  /character:
    get:
      summary: Get all characters
      description: Get all characters
      tags:
        - character
      security:
        - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Character'
        '400':
          description: Input Error. Check the request payload for issues.
        '401':
          description: Authorization information is missing or invalid.
          content:
            application/json:
                schema:
                    $ref: '#/components/schemas/Unauthorized'
        '403':
          description: >-
            Access denied. Additional priviledges are needed access the
            requested resource.
        '404':
          description: Not Found. The requested resource does not exist.
        '429':
          description: Rate Limited. Too many requests.
        '500':
          description: Unexpected error
    post:
      summary: Create a new character
      description: |
        Create a new character.

        Required properties are: `life_goal`.
      tags:
        - character
      security:
        - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Character'
        '400':
          description: Input Error. Check the request payload for issues.
          content:
            application/json:
                schema:
                    $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Authorization information is missing or invalid.
          content:
            application/json:
                schema:
                    $ref: '#/components/schemas/Unauthorized'
        '403':
          description: >-
            Access denied. Additional priviledges are needed access the
            requested resource.
        '404':
          description: Not Found. The requested resource does not exist.
        '429':
          description: Rate Limited. Too many requests.
        '500':
          description: Unexpected error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - description
                - properties
              properties:
                name:
                  type: string
                  description: "The character's name"
                description:
                  type: string
                  description: "The character's bio"
                properties:
                  type: array
                  description: |
                    Properties of the character. These can be anything you want!
                    
                    Required properties are: `life_goal`
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        description: "The name of the property"
                      value:
                        type: string
                        description: "The value of the property"
  /chat:
    get:
      summary: Get all chats
      description: Get all chats
      tags:
        - chat
      security:
        - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
        '400':
          description: Input Error. Check the request payload for issues.
        '401':
          description: Authorization information is missing or invalid.
          content:
            application/json:
                schema:
                    $ref: '#/components/schemas/Unauthorized'
        '403':
          description: >-
            Access denied. Additional priviledges are needed access the
            requested resource.
        '404':
          description: Not Found. The requested resource does not exist.
        '429':
          description: Rate Limited. Too many requests.
        '500':
          description: Unexpected error
    post:
      summary: Start a chat with your character
      description: Start a chat with your character
      tags:
        - chat
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - characterId
              properties:
                characterId:
                  type: string
                  description: "The character's id"
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
        '400':
          description: Input Error. Check the request payload for issues.
        '401':
          description: Authorization information is missing or invalid.
          content:
            application/json:
                schema:
                    $ref: '#/components/schemas/Unauthorized'
        '403':
          description: >-
            Access denied. Additional priviledges are needed access the
            requested resource.
        '404':
          description: Not Found. The requested resource does not exist.
        '429':
          description: Rate Limited. Too many requests.
        '500':
          description: Unexpected error
  /chat/{chat_id}:
    get:
      summary: Get a chat and its messages
      description: Get all information for a chat
      tags:
        - chat
      security:
        - bearerAuth: []
      parameters:
        - name: chat_id
          in: path
          description: ''
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
        '400':
          description: Input Error. Check the request payload for issues.
        '403':
          description: >-
            Access denied. Additional priviledges are needed access the
            requested resource.
        '404':
          description: Not Found. The requested resource does not exist.
        '429':
          description: Rate Limited. Too many requests.
        '500':
          description: Unexpected error
    post:
      summary: Reply to your AI friend
      description: |-
        Reply to your AI friend
        <br /><br />
        <b>Authentication:</b> required
      tags:
        - chat
      security:
        - bearerAuth: []
      parameters:
        - name: chat_id
          in: path
          description: ''
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    description: 'Your message to your character'
                    $ref: '#/components/schemas/Message'
                  response:
                    description: 'Your character''s response'
                    $ref: '#/components/schemas/Message'                  

        '400':
          description: Input Error. Check the request payload for issues.
        '403':
          description: >-
            Access denied. Additional priviledges are needed access the
            requested resource.
        '404':
          description: Not Found. The requested resource does not exist.
        '429':
          description: Rate Limited. Too many requests.
        '500':
          description: Unexpected error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: 'Your message to your character'
          multipart/form-data:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: ''
    delete:
      summary: Delete a chat
      description: |-
        Delete a chat
        <br /><br />
        <b>Authentication:</b> required
      tags:
        - chat
      security:
        - bearerAuth: []
      parameters:
        - name: chat_id
          in: path
          description: ''
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '400':
          description: Input Error. Check the request payload for issues.
        '403':
          description: >-
            Access denied. Additional priviledges are needed access the
            requested resource.
        '404':
          description: Not Found. The requested resource does not exist.
        '429':
          description: Rate Limited. Too many requests.
        '500':
          description: Unexpected error